### PR TITLE
Add configuration options to reporter

### PR DESCRIPTION
**Pull request by hollandjake**
- Added configuration to the reporter so we can configure what is reported
- Added support for reporting the ops/seconds

### CODE REVIEW

**Comment by pckhoi** [comment]
Nice! Could you provide some screenshots how that op/sec would look like?

**Comment by hollandjake** [comment]
image

We could change the order if you would like it elsewhere (or maybe it should be configurable ;) )

**Comment by pckhoi** [comment]
It's fine. You can add that functionality in a future PR if you want ;)

**Comment by hollandjake** [comment]
as an fyi, in regards to this PR, it maintains backwards compatibility so any old scripts using it wont change their output

**Comment by pckhoi** [comment]
This change is in jest-bench@29.7.0

**Pull request merged**
